### ISSUE TITLE
Question on evaluation

### ISSUE THREAD

**Issue by alanakbik** [nusnlp/contextemb-wsd#2]
Thanks for making this repo available! 

I have a question regarding evaluation on the different semeval datasets (SE07 SE2 SE3 SE13 SE15): 

How do you deal with differences in annotation schema between SemCor and the semeval datasets? For instance, in SemCor person names are labeled "person%1:03:00::" whereas in semeval 2013 there are unlabeled. A model trained on SemCor will therefore predict "person%1:03:00::" for names in semeval 2013. Do these count as errors? Or do you exclude them from evaluation?

I am asking since we want to implement something similar in [Flair](https://github.com/flairNLP/flair), but I am not sure how to compute the evaluation numbers properly.

**Comment by chrhad** [comment]
We do not count such instances as errors as we only tag those words with instance ID, that is, those inside XML tags <instance ...> </instance>. We evaluated our experiments in the test data provided [here](http://lcl.uniroma1.it/wsdeval/evaluation-data). So in other words, you are right, we exclude them from the evaluation.

The evaluation scores are computed using the provided evaluation code in the zipped file downloadable through the same link (written in Java).

Hope this helps.

**Comment by alanakbik** [comment]
Hello @chrhad thanks for the clarification! This makes sense and I assume this is standard procedure in WSD evaluations (I just couldn't find mention of this in all the WSD papers I've been reading). 

Just one more question: Is there special handling for senses that exist in the test data but not in the training data?

**Comment by chrhad** [comment]
For that case, we back-off to the most frequent sense according to the WordNet, which provides the frequency of each word sense. We give the back-off lookup table in the files ending with .mfs.txt

**Comment by alanakbik** [comment]
Awesome, thanks!
